#!/bin/bash

sudo rm -f /etc/apt/sources.list.d/docker.list
sudo rm -f /etc/apt/keyrings/docker.gpg
sudo rm -f /etc/apt/trusted.gpg.d/docker.gpg

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/docker.gpg > /dev/null

echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu noble stable" | \
sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt update
